### ISSUE TITLE
`test_query_e2e()` failing in CI on Mac

### ISSUE THREAD

**Issue by rlamy** [iterative/datachain#251] opened 2024-08-07 15:34 UTC
`test_query_e2e()` has started failing in CI on Mac today. That doesn't seem related to any recent change and I haven't been able to reproduce that locally.

**Comment by dtulga** [comment] 2024-08-08 15:39
Closing as done with #254 and #211 (as it is fixed now, and I can't reproduce the problem locally.)

**Closed by dtulga** 2024-08-08 15:39 UTC
Labels: bug
