### ISSUE TITLE
Research: implement subtract on existing merge/join

### ISSUE THREAD

**Issue by dmpetrov** [iterative/datachain#269] opened 2024-08-11 00:51 UTC
We need to research these areas:

- [ ] `subtract()` uses custom machinery and runs sql-join under the hood. Can we level this up to application level and use existing datachain merge/join?

- [ ] user might need several outputs like `git diff` - added, removed, changed. We need a diff command that supports all of these like `ch1.diff(ch2, status="ad")` (added and deleted files only). 

The result of this issue should be a proposal for (1) and (2), not implementation.

**Comment by dreadatour** [comment] 2024-12-03 05:55
Might be a duplicate of https://github.com/iterative/datachain/issues/636

**Closed** 2024-12-04 01:03 UTC
Labels: question
