### ISSUE TITLE
Column type inference fails after using mutate to subtract two columns

### ISSUE THREAD

**Issue by tibor-mach** [iterative/datachain#148] opened 2024-07-23 08:29 UTC
### Description

I am creating two columns with `cosine_distance` and then I try to create a new column by subtracting one from the other. The code looks like this:

```
from sqlalchemy import func

embeddings_differences = (
    DataChain
    .from_dataset("embeddings")
    .mutate(
        query_sim_new = 1 - cosine_distance(C.document.embeddings_new, embedded_query_new),
        query_sim_old = 1 - cosine_distance(C.document.embeddings_old, embedded_query_old),
        )
    .mutate(abs_difference = func.abs(C.query_sim_old - C.query_sim_new))
    .save("embeddings-differences")
)
```

After running this I get this error:

```
CompileError: (in table 'ds_embeddings-differences_1', column 'abs_difference'): Can't generate DDL for NullType(); did you forget to specify a type on this Column?
```

This fails even if I remove `func.abs`, i.e. when this is just an ordinary subtraction of the two columns. If I try to save the dataset after the first `.mutate`, load it and then save it as a different dataset after calling the second `.mutate` it fails as well.

If I simply try to show the results with `.show` or convert it to pandas, it works as expected.

How to reproduce:

Run [this notebook](https://github.com/iterative/datachain/blob/llm-tutorial/examples/llm/llm_chatbot_evaluation.ipynb) and see the output of the cell with the code above.

### Version Info

```Text
0.2.12.dev36+g0b3cf72
Python 3.12.4
```

**Comment by ilongin** [comment] 2024-07-23 12:37
@tibor-mach  Added PR https://github.com/iterative/datachain/pull/152

This PR just adds better error handling for this as I don't think we can fix it in better way.
The workaround, and only solution I think is valid, is to manually cast to specific type when type cannot be infered, like in subtract example.

Until we have `cast` function in `DataChain` (PR is merged) you can use it from `SQLAlchemy` directly, e.g `from sqlalchemy import cast`. Examples of how to cast to specific types are in the PR

**Comment by tibor-mach** [comment] 2024-07-23 12:49
@ilongin hmm, this is kind of awkward, particularly with these simple operations it is kind of a hassle to have to manually cast the output. I wonder if we couldn't just include our custom automatic inference. 

But I will use the workaround for now ,thanks!

**Comment by dmpetrov** [comment] 2024-07-23 13:02
That's right! We need to handle it under the hood, not through a new API call.

**Comment by dmpetrov** [comment] 2024-07-26 00:28
@tibor-mach I was not able to reproduce it.

This seems return a correct result:
```
from sqlalchemy import func

embeddings1 = [[1.0, 2.0, 3.0], [4.0, 5.0, 6.0], [7.0, 8.0, 9.0]]
embeddings2 = [[0.0, 0.1, 0.2], [0.3, 0.4, 0.5], [0.6, 0.7, 0.8]]

chain = DataChain.from_values(emd1=embeddings1, emd2=embeddings2)

ch = chain.mutate(x=func.abs(1 - cosine_distance(C.emd1, C.emd2)))
ch.collect("x")
```

Also < I did.n't find the example in the notebook.

I'd really appreciate it if you could provide a reproducible code.

**Comment by tibor-mach** [comment] 2024-07-26 12:01
@dmpetrov It is a bit awkward to reference to specific lines of code in notebooks, but [here](https://github.com/iterative/datachain/blob/f0adb7d6d5bfa406d1a98ea488d01e5d37f6be1f/examples/llm/llm_chatbot_evaluation.ipynb#L556-L573) is where the relevant bit is. 

Just run the entire notebook up to that point, it should be reproducible that way.

**Comment by dmpetrov** [comment] 2024-07-26 19:21
@tibor-mach thank you for the reference. However, I was unable to run this notebook - too many dependencies issue. (It's especially surprising since this notebook was merged to the repository 🙂 )

Could you please narrow it down to a reproducible example? I would greatly appreciate it.

**Comment by ilongin** [comment] 2024-07-27 08:59
@dmpetrov error happens on .save(). When I get to my laptop I can send some simple examples that are failing but I think yours will as well on .save()

**Comment by dmpetrov** [comment] 2024-07-27 18:19
@ilongin thank you! This is a minimum reproducible example:

```
def test_ddd():
    fib = [1, 1, 2, 3, 5, 8]
    chain = DataChain.from_values(num=fib)
    chain = DataChain.from_values(num=fib)

    ch = chain.mutate(add2=Column("num") - 2)
    ch = ch.save()
    assert list(ch.collect("add2")) == [x - 2 for x in fib]
```

**Comment by dmpetrov** [comment] 2024-07-27 20:24
I see two ways of solving this issue and we need both of the method (1 is a prerequisite to 2):

1. Getting typed-columns from chain.

```python
chain =  DataChain.from_storage("s3://ldb-public/remote/data-lakes/dogs-and-cats/", anon=True)

(  chain
    .mutate(size_diff = chain.column("file.size") - 2)  # DataCHain.column() resolves columns AND types
    .save("example")
)
```

2. 
Do this (1) conversion under the hood.

mutate() should get this no-typed expression and convert it to typed (as in (1)).
Like: `mutate(y=Column("x") - 1)` --> `mutate(y=self.column("x") - 1)`

User shouldn't not see that:
```python
chain =  DataChain.from_storage("s3://ldb-public/remote/data-lakes/dogs-and-cats/", anon=True)

(  chain
    .mutate(size_diff = Column("file.size") - 2)
    .save("example")
)
```

(1) seems easy to implement. (2) they might be some sqlalchemy-specific risks but I don't see any conceptual issues.

@ilongin what should we do with #152? Would you prefer to re-implement it or close and work on a new one?

**Comment by ilongin** [comment] 2024-07-27 23:11
@dmpetrov you are right, expression was not typed because column didn't have type,  I totally missed that because addition and multiplication expressions had types regardless of column being without type for some reason.

I will close current PR and reopen

**Comment by ilongin** [comment] 2024-07-27 23:20
One problem that I discovered though is that function types seems to be `NullType()` regardless if argument (expression) is types.

Example which fails although column has explicit type:
```python
def test_ddd():
    from sqlalchemy import func
    from datachain.sql.types import Int
    fib = [1, 1, 2, 3, 5, 8]
    chain = DataChain.from_values(num=fib)

    ch = chain.mutate(add2=func.abs(Column("num", Int) - 2))
    ch = ch.save()
    assert list(ch.collect("add2")) == [x - 2 for x in fib]
```

**Comment by dmpetrov** [comment] 2024-07-30 03:59
I hope we can overcome this. If not - we have to implement (2). Basically - derive the type ourselves.

In case this is not possible, reimplementing Columns will be our only option iterative/dvcx#1637

**Closed** 2024-08-06 12:48 UTC
Labels: bug
